version: '3'

services:
  login-service:
    tty: true
    image: bitnami/laravel:latest
    depends_on:
      - user-management-service
    ports:
      - 3000:3000
    volumes:
      - ./login-service:/app

  user-management-service:
    tty: true
    image: bitnami/laravel:latest
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
    depends_on:
      - mariadb
    volumes:
      - ./user-management-service:/app

  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_PASSWORD=my_password
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - backend

networks:
  backend:
    driver: host