version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./login-service:/var/www/login-service
      - ./nginx/nginx-new.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/login-service.conf:/etc/nginx/conf.d/login-service.conf
      - ./nginx/ssl/:/etc/nginx/certs/
      - ./nginx/docker-entrypoint.sh:/docker-entrypoint.d/docker-entrypoint.sh
    networks:
      - app-network
  
  login-service:
    build:
      context: login-service
      dockerfile: Dockerfile
    container_name: login-service
    depends_on:
      - webserver
      - mysql
    tty: true
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: connection_security
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - app-network

networks:
  app-network:
    driver: bridge