version: '3'

services:
  login-service:
    tty: true
    image: bitnami/laravel:latest
    volumes:
      - ./login-service:/app
    networks:
    - frontnet     

  user-management-service:
    tty: true
    image: bitnami/laravel:latest
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=my_user
      - DB_DATABASE=connection_security
      - DB_PASSWORD=my_password
    depends_on:
      - mariadb
    volumes:
      - ./user-management-service:/app
    networks:
      - frontnet
      - backnet

  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=connection_security
      - MARIADB_PASSWORD=my_password
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - backnet

networks:
  backnet:
  frontnet: